[package]
name = "vec-repeat-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.vec-repeat]
path = ".."

[dependencies.mx-sc-debug]
version = "0.38.0"
path = "../../../../../framework/debug"
