[package]
name = "forwarder"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@elrond.com>"]
edition = "2021"
publish = false

[lib]
path = "src/forwarder_main.rs"

[features]
ei-unmanaged = ["elrond-wasm/ei-unmanaged"]

[dependencies.vault]
path = "../vault"

[dependencies.elrond-wasm]
version = "0.38.0"
path = "../../../../framework/base"

[dev-dependencies.elrond-wasm-debug]
version = "0.38.0"
path = "../../../../framework/debug"

