[package]
name = "esdt-transfer-with-fee-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.esdt-transfer-with-fee]
path = ".."

[dependencies.mx-sc-debug]
version = "0.38.0"
path = "../../../../framework/debug"
