[settings]
main = "main"

[contracts.main]
name = "multisig"
add-unlabelled = true

[contracts.full]
name = "multisig-full"
add-unlabelled = true
add-labels = ["additionalView"]

[contracts.view]
name = "multisig-view"
external-view = true
add-labels = ["additionalView"]
