[package]
name = "kitty-auction-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.kitty-auction]
path = ".."

[dependencies.mx-sc-debug]
version = "0.38.0"
path = "../../../../../framework/debug"
