[package]
name = "forwarder-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.forwarder]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.5"
path = "../../../../../framework/meta"
