[package]
name = "bonding-curve-contract"
version = "0.0.0"
authors = ["Alin Cruceat <alin.cruceat@elrond.com>"]
edition = "2021"
publish = false

[lib]
path = "src/bonding_curve_contract.rs"

[dependencies.elrond-wasm]
version = "0.38.0"
path = "../../../framework/base"

[dependencies.mx-sc-modules]
version = "0.38.0"
path = "../../../contracts/modules"

[dev-dependencies.elrond-wasm-debug]
version = "0.38.0"
path = "../../../framework/debug"

