[package]
name = "fractional-nfts"
version = "0.0.0"
authors = ["Claudiu-Marcel Bruda <claudiu.bruda@elrond.com>"]
edition = "2021"
publish = false

[lib]
path = "src/fractional_nfts.rs"

[dependencies.elrond-wasm]
version = "0.37.0"
path = "../../../elrond-wasm"

[dependencies.elrond-wasm-modules]
version = "0.37.0"
path = "../../../elrond-wasm-modules"

[dev-dependencies.elrond-wasm-debug]
version = "0.37.0"
path = "../../../elrond-wasm-debug"
