[settings]
main = "main"

[contracts.main]
name = "multi-contract-features"
add-unlabelled = true

[contracts.multi-contract-features-view]
# name is optional, if missing this ^^^ id will be used
external-view = true
add-labels = ["mcs-external-view"]
