[package]
name = "use-module"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2021"
publish = false

[lib]
path = "src/use_module.rs"

[dependencies.mx-sc-modules]
version = "0.38.0"
path = "../../../contracts/modules"

[dependencies.mx-sc]
version = "0.38.0"
path = "../../../framework/base"
features = [ "alloc" ]

[dev-dependencies.mx-sc-scenario]
version = "0.38.0"
path = "../../../framework/scenario"

[dev-dependencies.mx-sc-meta]
version = "0.38.0"
path = "../../../framework/meta"
