[package]
name = "rewards-distribution"
version = "0.0.0"
authors = ["Claudiu-Marcel Bruda <claudiu.bruda@elrond.com>"]
edition = "2021"
publish = false

[lib]
path = "src/rewards_distribution.rs"

[dependencies.elrond-wasm]
version = "0.38.0"
path = "../../../framework/base"

[dependencies.elrond-wasm-modules]
version = "0.38.0"
path = "../../../contracts/modules"

[dev-dependencies.elrond-wasm-debug]
version = "0.38.0"
path = "../../../framework/debug"
