[package]
name = "rewards-distribution"
version = "0.0.0"
authors = ["Claudiu-Marcel Bruda <claudiu.bruda@multiversx.com>"]
edition = "2021"
publish = false

[lib]
path = "src/rewards_distribution.rs"

[dependencies.mx-sc]
version = "0.38.0"
path = "../../../framework/base"

[dependencies.mx-sc-modules]
version = "0.38.0"
path = "../../../contracts/modules"

[dev-dependencies.mx-sc-scenario]
version = "0.38.0"
path = "../../../framework/scenario"
