[package]
name = "mx-wegld-swap-sc-meta"
version = "0.0.0"
authors = [ "Dorin Iancu <dorin.iancu@multiversx.com>",]
edition = "2021"
publish = false

[dev-dependencies]

[dependencies.mx-wegld-swap-sc]
path = ".."

[dependencies.mx-sc]
version = "0.38.0"
path = "../../../../framework/base"

[dependencies.mx-sc-meta]
version = "0.38.0"
path = "../../../../framework/meta"
