[package]
name = "token-release-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dev-dependencies]

[dependencies.token-release]
path = ".."

[dependencies.mx-sc-debug]
version = "0.38.0"
path = "../../../../framework/debug"

