[package]
name = "elrond-sc-price-aggregator-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.elrond-sc-price-aggregator]
path = ".."

[dependencies.elrond-wasm]
version = "0.38.0"
path = "../../../../framework/base"

[dependencies.mx-sc-debug]
version = "0.38.0"
path = "../../../../framework/debug"
