[package]
name = "mx-price-aggregator-sc-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.mx-price-aggregator-sc]
path = ".."

[dependencies.mx-sc]
version = "0.38.0"
path = "../../../../framework/base"

[dependencies.mx-sc-meta]
version = "0.38.0"
path = "../../../../framework/meta"
