[package]
name = "formatted-message-features"
version = "0.0.0"
authors = [ "you",]
edition = "2021"
publish = false

[lib]
path = "src/formatted_message_features.rs"

[dependencies.elrond-wasm]
version = "0.38.0"
path = "../../../framework/base"

[dev-dependencies.mx-sc-debug]
version = "0.38.0"
path = "../../../framework/debug"
