[package]
name = "elrond-sc-price-aggregator"
version = "0.38.0"
authors = [
    "Claudiu-Marcel Bruda <claudiu.bruda@elrond.com>",
    "Elrond Network <contact@elrond.com>",
]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/ElrondNetwork/elrond-wasm-rs"
homepage = "https://elrond.com/"
documentation = "https://docs.elrond.com/"
description = "Elrond Price aggregator Smart Contract"
keywords = ["elrond", "wasm", "webassembly", "blockchain", "contract"]
categories = ["no-std", "wasm", "cryptography::cryptocurrencies"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.38.0"
path = "../../../framework/base"

[dependencies.mx-sc-modules]
version = "0.38.0"
path = "../../../contracts/modules"

[dev-dependencies.elrond-wasm-debug]
version = "0.38.0"
path = "../../../framework/debug"

[dependencies]
arrayvec = { version = "0.7.1", default-features = false }
