[package]
name = "lottery-esdt"
version = "0.0.0"
authors = [ "Dorin Iancu <dorin.iancu@multiversx.com>",]
edition = "2021"
publish = false

[lib]
path = "src/lottery.rs"

[dependencies.mx-sc]
version = "0.38.0"
path = "../../../framework/base"

[dev-dependencies.mx-sc-scenario]
version = "0.38.0"
path = "../../../framework/scenario"
