[package]
name = "child-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.child]
path = ".."

[dependencies.elrond-wasm]
version = "0.38.0"
path = "../../../../../../framework/base"

[dependencies.elrond-wasm-debug]
version = "0.38.0"
path = "../../../../../../framework/debug"
