[package]
name = "mxpy-snippet-generator"
version = "0.0.0"
authors = ["Dorin Marian Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"
publish = false

[[bin]]
name = "mxpy-snippet-generator"
path = "src/mxpy_snippet_generator.rs"

[dependencies.multiversx-sc]
version = "0.39.1"
path = "../../framework/base"

[dependencies.multiversx-chain-vm]
version = "0.1.1"
path = "../../vm"

[dependencies]
bech32 = "0.9"
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"
