[package]
name = "empty"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[lib]
path = "src/empty.rs"

[dependencies.elrond-wasm]
version = "0.38.0"
path = "../../../framework/base"

[dev-dependencies.elrond-wasm-debug]
version = "0.38.0"
path = "../../../framework/debug"

[dev-dependencies]
num-bigint = "0.4.2"
