[package]
name = "erdpy-snippet-generator"
version = "0.0.0"
authors = ["Dorin Marian Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"

[[bin]]
name = "erdpy-snippet-generator"
path = "src/erdpy_snippet_generator.rs"

[dependencies.mx-sc]
version = "0.38.0"
path = "../../framework/base"

[dependencies.mx-chain-vm]
version = "0.38.0"
path = "../../vm"

[dependencies]
bech32 = "0.8.1"
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"
