[package]
name = "str-repeat-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.str-repeat]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.3"
path = "../../../../framework/meta"
