[package]
name = "basic-features"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@elrond.com>"]
edition = "2021"
publish = false

[lib]
path = "src/basic_features_main.rs"

[dependencies.elrond-wasm]
version = "0.38.0"
path = "../../../framework/base"

[dev-dependencies.elrond-wasm-debug]
version = "0.38.0"
path = "../../../framework/debug"

[dependencies.elrond-wasm-modules]
version = "0.38.0"
path = "../../../contracts/modules"

[dev-dependencies.esdt-system-sc-mock]
path = "../esdt-system-sc-mock"
