[package]
name = "lottery-esdt-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@elrond.com>"]
edition = "2021"
publish = false

[dependencies.lottery-esdt]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.38.0"
path = "../../../../framework/debug"
