[package]
name = "format-tests"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "format-tests"
path = "src/format_tests.rs"

[dependencies.mx-sc]
version = "0.38.0"
path = "../../../framework/base"

[dependencies.mx-chain-vm]
version = "0.38.0"
path = "../../../vm"

[dev-dependencies]
glob = "0.3.0"
home = "0.5.3"

[workspace]
members = ["."]
