[package]
name = "parent-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.parent]
path = ".."

[dependencies.mx-sc]
version = "0.38.0"
path = "../../../../../../framework/base"

[dependencies.mx-sc-debug]
version = "0.38.0"
path = "../../../../../../framework/debug"
