[package]
name = "erc721-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@elrond.com>"]
edition = "2021"
publish = false

[dependencies.erc721]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.38.0"
path = "../../../../../framework/debug"
