[package]
name = "multiversx-sc-upgrade"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sc-upgrade"
path = "src/sc_upgrade_main.rs"

[dependencies.multiversx-sc-meta]
version = "0.39.0"
path = "../../framework/meta"

[dependencies]
ruplacer = "0.8.1"
clap = { version = "4.1.0", features = ["derive", "cargo"] }
toml = { version = "0.5.8", features = ["preserve_order"] }
