[package]
name = "vault"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@elrond.com>"]
edition = "2021"
publish = false

[lib]
path = "src/vault.rs"


[dependencies.elrond-wasm]
version = "0.38.0"
path = "../../../../framework/base"

[dev-dependencies.elrond-wasm-debug]
version = "0.38.0"
path = "../../../../framework/debug"
